#springboot整合rabbitmq的基本配置
spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    virtual-host: /
    #rabbitmq消费端配置
    listener:
      simple:
        #最大并发数
        concurrency: 5
        #manual:手动签收 ack(不然当消费者接收消息后将自动提交ack确认，MQ将删除此条消息）
        acknowledge-mode: manual
        max-concurrency: 10
        #同一时间deliveryTag最大值（限流）
        prefetch: 10
  datasource:
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1qaz@WSX
      driverClassName: com.mysql.jdbc.Driver
server:
  port: 8081
  servlet:
    context-path: /